name: test_utils
description: Commonly used test functions
version: 0.0.1
homepage: mehmetesen.com

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
