name: test_utils
description: Commonly used test functions
version: 1.0.0
homepage: http://mehmetesen.com
repository: https://github.com/esenmx/test_utils/

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  mockito: ^5.4.2
  test: ^1.23.0
  riverpod: ^2.3.6

dev_dependencies:
  lints: ^2.1.1
