name: test_utils
description: Commonly used test functions
version: 1.0.0
homepage: http://mehmetesen.com
repository: https://github.com/esenmx/test_utils/

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  mockito:
  test:
  riverpod:

dev_dependencies:
  lints:
