name: test_utils
description: Commonly used test functions
version: 0.0.1
homepage: mehmetesen.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  mockito: ^5.1.0

dev_dependencies:
  lints: ^1.0.1
